module.exports = {
  apps: [
    {
      name: "api-server",
      cwd: "./artifacts/api-server",
      script: "./dist/index.mjs",
      interpreter: "node",
      interpreter_args: "--enable-source-maps",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: "5001",
        DATABASE_URL: "postgresql://postgres:postgres123@localhost:5432/res_db",
        SESSION_SECRET: "dev-secret-change-in-prod",
      },
      error_file: "./logs/api-server-error.log",
      out_file: "./logs/api-server-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      max_restarts: 10,
      restart_delay: 4000,
    },
    {
      name: "frontend",
      cwd: "./artifacts/resident-voice",
      script: "pnpm",
      args: "run serve",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: "5173",
        BASE_PATH: "/",
      },
      error_file: "./logs/frontend-error.log",
      out_file: "./logs/frontend-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      max_restarts: 10,
      restart_delay: 4000,
    },
  ],
};
